### PR TITLE
0.2.5

### PR DESCRIPTION
**Pull request by BehindTheMath**

### CODE REVIEW

**Comment by BehindTheMath** [comment]
>Nice work guys!

Thank you!

>That said, I think you should cut a 1.0.0 and use semver more seriously than I did in the past :)

All the commits we made since 0.2.4 were really bug fixes and code cleanup, so I thought it would be better to wait to bump to 1.0.0 so that the update would go out to anyone currently using 0.2.4.

**Comment by robinnorth** [comment]
Thanks @MoOx! It certainly feels like it could be a 1.0.0 with the amount of changes made and effort put in, and I'm all for using SemVer religiously from now on, but @BehindTheMath does make a good point about 0.2.4 users getting the update automatically. 

That being said, 1.0.0 is a nice symbolic bump and 0.2.4 users can manually upgrade if there's a particular fix they've been waiting for...

**Comment by BehindTheMath** [comment]
Version 0.2.5 has been released to NPM.

**Comment by robinnorth** [comment]
Fantastic, nice work all! 🎉

**Pull request merged**
