### PR TITLE
Patch 51

### PR DESCRIPTION
**Pull request by darylteo**
Fixing a bunch of completely breaking errors as listed in #51

Also includes a very basic switch-selectors test.

### CODE REVIEW

**Comment by MoOx** [comment]
Great job. Thanks !

**Comment by MoOx** [comment]
Not sure if you want a new release now.
Where you using 0.1.4 or 0.2.0 ?
If you plan to make things better, I can add you as a collaborator.

**Comment by MoOx** [comment]
Ping me if you want me to cut a release.

**Comment by darylteo** [comment]
@moOx Please do that will speed things up. But my involvement will extend
up to the point where we decide that pjax will work on our application (I'm
on company time)

I just started using 0.2 branch

**Comment by MoOx** [comment]
@darylteo I added you as a collab. Here is what I ask for now:

- use PR all the times
- your PR should includes CHANGELOG notes if you fix a bug (Fixed: ...) or add a feature (Added:...) or change something (Changed: ..)

Are you familiar with semver?

**Comment by darylteo** [comment]
Familiar enough I hope.

Do you prefer large PRs or small feature PRs like what I just done?

**Comment by MoOx** [comment]
What you did is perfect and easier to review. I just pushed some updates to the CHANGELOG.
Feel free to link issue (and not PR) in the CHANGELOG when you commit something. And btw, one commit for fix + test is fine.

**Pull request merged**
