### PR TITLE
Add cacheBust option

### PR DESCRIPTION
**Pull request by tremby**
This addresses #70.

### CODE REVIEW

**Comment by MoOx** [comment]
I was about to cut a release but got this issue locally:

```
# test xhr request
# - request is made, gets a result, and is cache-busted
not ok 1 Error: TypeError: 'undefined' is not an object (evaluating 'r.responseURL.indexOf') on line 12906
```

Any idea if that can be cause by what you did here?

**Comment by MoOx** [comment]
(I think tests are running via safari on my machine, testling is choosing by itself)

**Comment by tremby** [comment]
The tests ran OK for me in Firefox. It's possible there's a bug. I'll look into this when I get time (in the next few days), if you don't find the issue before then.

**Comment by tremby** [comment]
It's working fine in Safari 9.1 but I can reproduce the problem in Safari 8. Looking into it.

**Comment by tremby** [comment]
I've fixed the test for Safari 8 in #73.

**Comment by MoOx** [comment]
Released in 0.2.4

**Pull request merged**
