### PR TITLE
Update tooling

### PR DESCRIPTION
**Pull request by BehindTheMath**
- Update browserify, serve, and tape to the latest versions
- Update the example script to reflect serve's new CLI options
- Remove the unneeded dependency on opn-cli
- Force Travis to use NPM 5.x

### CODE REVIEW

**Comment by BehindTheMath** [comment]
@MoOx now that we got rid of Testling, do we still need npmpub?

Also, Bower has been deprecated. Do we still need [bower.json](https://github.com/MoOx/pjax/blob/3bd101bb1d2f2fe8b93a9bab0371a8380f6869bd/bower.json)?

**Comment by MoOx** [comment]
npmpub have nothing to do with testling, it's to cut a release + create git tag + push CHANGELOG.md corresponding notes as a github release

I guess bower can die in peace :)

**Comment by BehindTheMath** [comment]
Ok. What about [this line](https://github.com/MoOx/pjax/blob/3bd101bb1d2f2fe8b93a9bab0371a8380f6869bd/package.json)?

**Comment by MoOx** [comment]
https://github.com/MoOx/pjax/pull/100 :)

**Pull request merged**
