### PR TITLE
Add switchElementsAlt() to the default switches

### LINKED ISSUE #83: Head tag keeps multiplying with empty contents
Hi, any idea why this would be happening?

head_problem_pjax

`var pjax = new Pjax({ selectors: ["head title", "body"] })` but it works the same if I remove the `head title`

### PR DESCRIPTION
**Pull request by BehindTheMath**
Fixes #83.

### CODE REVIEW

**Comment by BehindTheMath** [comment]
@MoOx I can't figure out why testling is erroring. This PR shouldn't affect that.

The affected tests are [here](https://github.com/MoOx/pjax/blob/a7b584c469d412ae7333a795a0ac8d3616a96a1f/tests/lib/request.js).

**Comment by MoOx** [comment]
@BehindTheMath since you have been added as a collaborator to this repo, you don't need to use your fork anymore and can cut a branch directly from this repo!

**Comment by MoOx** [comment]
It seems that CI found a regression. Note that testling should be used directly (see note in package.json) if you want to run existing tests

**Comment by BehindTheMath** [comment]
From the Travis logs, it looks like the regression was caused by #80. However, I don't see anything in that PR either that would cause this error.

Additionally, I ran testling locally in a VM, and it passed with no errors.

So I'm going to take the output of testling with a grain of salt, until it can be switched for an updated testing framework.

**Pull request merged**
