### PR TITLE
Replace instances of ES6 `const` keyword with `var`

### LINKED ISSUE #106: ES6 syntax in compiled build breaks compatibility with older browsers
It looks like some of the more recent changes to this library have introduced the use of the `const` keyword e.g. the in new `switchElementsAlt` method: https://github.com/MoOx/pjax/blob/b98e3ef9144553e3e8c70c82b04b5220f2dab589/lib/switches.js#L23

While this is not an issue of itself, the npm prepublish script doesn't include a transpiling step, meaning that these `const` keywords are still present in the compiled `pjax.js` build artifact.

To fix this and continue using ES6 syntax, the prepublish step could use Babel in conjunction with Browserify. Alternatively, the 3 instances of `const` in use could be replaced with `var` keywords.

### PR DESCRIPTION
**Pull request by robinnorth**
Fixes #106

### CODE REVIEW

**Comment by BehindTheMath** [comment]
Thanks.

**Comment by MoOx** [comment]
IMO we should keep es6 syntax and use babel to transpile for old browser when creating a bundle.

**Comment by BehindTheMath** [comment]
We can do that, but it will mean a major revamp of the code, which will include removing a bunch of legacy code, like the polyfills for `Function.prototype.bind`, and `Array.prototype.forEach`.

I think that should wait until we finish fixing all the existing issues, so we don't cause any conflicts. I'll open a new issue to track that.

**Comment by MoOx** [comment]
Make sense

**Pull request merged**
