### PR TITLE
Add Typescript definitions

### PR DESCRIPTION
**Pull request by BehindTheMath**

### CODE REVIEW

**Comment by BehindTheMath** [comment]
Never mind.

According to [Typescript's documentation](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html), if the package is not written in Typescript, it's preferable to add the type definitions to the DefinitelyTyped repo.

**Comment by BehindTheMath** [comment]
Actually, [DefinitelyTyped's recommendation](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/63ecc4d05dbd2571cc5533a9060823078cc72643#create-a-new-package) is:
>If you are the library author, or can make a pull request to the library, bundle types instead of publishing to DefinitelyTyped.

So I'm reopening this PR to add the definitions here.

**Comment by robinnorth** [comment]
LGTM, though I'm not a Typescript user. You might want to add a note to the readme to the effect that any PRs should ideally include updated Typescript definitions if necessary, in addition to passing tests.

**Comment by BehindTheMath** [comment]
I'm going to try to figure out if there's an easy way to write tests for this. Then we could include that in the testing workflow.

**Comment by BehindTheMath** [comment]
I haven't added any tooling for actually running or automating this test. To run it, Typescript would need to be installed, and I don't want to deal with that now.

To run it manually, install Typescript (either locally or globally), and then run:
```
tsc --noEmit ./tests/test.ts
```

**Pull request merged**
